/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libreria;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
		Menaje menaje = new Menaje(22222, "platos carton", false);
		System.out.println(menaje);
		Alimentacion alimento = new Alimentacion(33333333, "papas", true);
		System.out.println(alimento);
	}
}
